name: automatic release
on:
  push:
    branches:
      - master
    tags:
      - "!*"
jobs:
  release:
    name: check version and tagging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
      - name: install can-npm-publish and dependencies
        run: |
          npm install -D can-npm-publish
          npm ci
      - name: check version and add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ./packages/node/tools/release.sh
      - name: build
        run: npm run build:node
      - name: release
        run: npm publish --workspace=packages/node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
