name: automatic release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: release-playground
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
      - name: caching
        uses: google/wireit@setup-github-actions-caching/v1
      - name: install dependencies
        run: npm ci
      - name: check target list
        run: rustup target list
      - name: add target list
        run: rustup target add wasm32-wasi
      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: build - playground
        run: npm run build:playground
      - name: publish - playground
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=packages/playground/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
