name: automatic release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: release-node
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
      - name: caching
        uses: google/wireit@setup-github-actions-caching/v1
      - name: install dependencies
        run: npm ci
      - name: add target
        run: rustup target add wasm32-wasi
      - name: release
        run: npm run publish:node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
